coverage:
  range: '75...100'
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
# * Well-known flags: project.<branch>, package.<branch>_<package-id>
# * Flags that are always defined: project.main, package.main_root
# ! Any upload using the "project.main" flag must also use "package.main_root"
flag_management:
  # * These rules will apply to all non-specially-configured flags
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
      - type: patch
        target: auto
