/**
 * The name of the command line interface.
 */
export const globalCliName = 'symbiote';

/**
 * The CLI-wide namespace that appears in logger output.
 */
export const globalLoggerNamespace = globalCliName;

/**
 * The CLI-wide namespace that appears in debugger output.
 */
export const globalDebuggerNamespace = globalCliName;

/**
 * A regular expression matching any tstyche test file.
 */
// ! Cannot use the global (g) flag
export const tstycheTargetRegExp = /(^|\/)type(-.*)?\.test\.tsx?$/;

/**
 * The comment injected before each batch of auto-generated aliases.
 */
export function makeGeneratedAliasesWarningComment(spaces: number) {
  const space = ' '.repeat(spaces);

  return `${space}// ! These aliases are auto-generated by symbiote. Instead of modifying them
${space}// ! directly, consider regenerating aliases across the entire project with:
${space}// ! \`npx symbiote project renovate --regenerate-assets --assets-preset ...\`
`.trimEnd();
}
